import type { Metadata } from "next";
import "./globals.css";
import localFont from 'next/font/local'
import HackerBackground from "@/components/ui/hackerbg";

const protestRevolution = localFont({
  src: './fonts/ProtestRevolution-Regular.ttf',
  display: 'swap',
  variable: '--font-protest-revolution',
})

const archivoBlack = localFont({
  src: './fonts/ArchivoBlack-Regular.ttf',
  display: 'swap',
  variable: '--font-archivo-black',
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${protestRevolution.variable} ${archivoBlack.variable}`}>
      <body className="relative bg-black">
        <HackerBackground color="#8364FF" fontSize={8} speed={1} className="opacity-1 bg-transparent" />
        {children}
      </body>
    </html>
  );
}
